version: '3.8'
services:
  postgres:
    image: postgres:16.1
    container_name: shareit-postgres
    ports:
      - "6432:5432"
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: gg
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: